### ISSUE TITLE
Créer des tags ET des releases

### ISSUE THREAD

**Issue by babeuloula** [Grafikart/filemanager-element#11]
Salut,

Afin d'être maintenu à jour des nouveautés de la lib, est-il possible de publier des releases en même temps que les tags ? Cela permet de watch de le repo et d'avoir une notif quand une nouvelle version est dispo.

Par défaut, Github ne permet pas de watch sur un tag.

Merci

**Comment by Grafikart** [comment]
J'ai mis en place un workflow pour créer des releases automatiquement. Je te laisse fermer si cela te convient

**Comment by babeuloula** [comment]
Parfait, j'ai reçu le mail de Github pour la release. Je ferme.
