### ISSUE TITLE
Tokens ou Headers personnalisé

### ISSUE THREAD

**Issue by lepresk** [Grafikart/filemanager-element#2]
Comment associer un header personnalité ou un token type csrf à la requête qui est envoyé au serveur pour des besoins de protection ou d'authentification!

**Comment by Grafikart** [comment]
Tu pourrais le mettre dans les cookies car la requête est envoyé avec un credentials: include.

Sinon on peut imaginer pouvoir modifier le fetcher via une méthode dédié. La signature ressemblerait à ça :

```ts
FileManager.fetcher = (url: string, options: object) => Promise<Response>
```

Si tu as une autre idée avant que j'implémente la chose je suis ouvert aux proposition.

**Comment by lepresk** [comment]
Redéfinir tout le `fetcher` est un peu violent pour celui qui va utilisé le plugin je trouve (surtout pour les gens avec peu d'expérience), ce qui m'arrangerait par exemple c'est d'avoir quelque chose qui ressemble à ceci :

`FileManager.additionalHeaders = Object`

**Comment by Grafikart** [comment]
J'ai ajouté l'option `httpHeaders` dans les options de la fonction register. Je te laisse regarder la doc et me dire si cela solutionne ta problématique.
